"""phase2_all_domain_models

Revision ID: a09e53ccd3b7
Revises: 
Create Date: 2026-08-25 08:46:36.494995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a09e53ccd3b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('razorpay_merchant_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_razorpay_merchant_id'), 'merchants', ['razorpay_merchant_id'], unique=True)
    op.create_index(op.f('ix_merchants_status'), 'merchants', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credential_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('allowed_tools', sa.Text(), nullable=False),
    sa.Column('max_payment_attempts_per_hour', sa.Integer(), nullable=False),
    sa.Column('max_tool_calls_per_minute', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_hash')
    )
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_index(op.f('ix_agents_user_id'), 'agents', ['user_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('discount_type', sa.String(length=16), nullable=False),
    sa.Column('discount_value', sa.Integer(), nullable=False),
    sa.Column('max_discount_minor', sa.Integer(), nullable=False),
    sa.Column('eligible_categories', sa.Text(), nullable=False),
    sa.Column('eligible_product_ids', sa.Text(), nullable=False),
    sa.Column('max_uses_per_agent_per_day', sa.Integer(), nullable=False),
    sa.Column('max_total_uses', sa.Integer(), nullable=False),
    sa.Column('total_uses', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_code'), 'campaigns', ['code'], unique=False)
    op.create_index(op.f('ix_campaigns_merchant_id'), 'campaigns', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('catalog_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('availability', sa.String(length=32), nullable=False),
    sa.Column('agent_purchase_allowed', sa.Boolean(), nullable=False),
    sa.Column('eligible_campaign_ids', sa.Text(), nullable=False),
    sa.Column('upsell_product_ids', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_products_availability'), 'catalog_products', ['availability'], unique=False)
    op.create_index(op.f('ix_catalog_products_category'), 'catalog_products', ['category'], unique=False)
    op.create_index(op.f('ix_catalog_products_merchant_id'), 'catalog_products', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_catalog_products_sku'), 'catalog_products', ['sku'], unique=False)
    op.create_table('merchant_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('agent_commerce_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_autonomous_order_minor', sa.Integer(), nullable=False),
    sa.Column('max_discount_pct', sa.Integer(), nullable=False),
    sa.Column('max_agent_txns_per_day', sa.Integer(), nullable=False),
    sa.Column('allowed_agent_categories', sa.Text(), nullable=False),
    sa.Column('allowed_payment_methods', sa.Text(), nullable=False),
    sa.Column('refund_requires_human', sa.Boolean(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_policies_is_current'), 'merchant_policies', ['is_current'], unique=False)
    op.create_index(op.f('ix_merchant_policies_merchant_id'), 'merchant_policies', ['merchant_id'], unique=False)
    op.create_table('spending_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spending_policies_is_active'), 'spending_policies', ['is_active'], unique=False)
    op.create_index(op.f('ix_spending_policies_user_id'), 'spending_policies', ['user_id'], unique=False)
    op.create_table('consent_mandates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('max_amount_per_txn_minor', sa.Integer(), nullable=False),
    sa.Column('max_daily_amount_minor', sa.Integer(), nullable=False),
    sa.Column('allowed_categories', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_mandates_agent_id'), 'consent_mandates', ['agent_id'], unique=False)
    op.create_index(op.f('ix_consent_mandates_merchant_id'), 'consent_mandates', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_consent_mandates_status'), 'consent_mandates', ['status'], unique=False)
    op.create_index(op.f('ix_consent_mandates_user_id'), 'consent_mandates', ['user_id'], unique=False)
    op.create_table('delegations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('max_transaction_minor', sa.Integer(), nullable=False),
    sa.Column('max_daily_spend_minor', sa.Integer(), nullable=False),
    sa.Column('max_monthly_spend_minor', sa.Integer(), nullable=False),
    sa.Column('require_consent_above_minor', sa.Integer(), nullable=False),
    sa.Column('allowed_categories', sa.Text(), nullable=False),
    sa.Column('allowed_merchant_ids', sa.Text(), nullable=False),
    sa.Column('blocked_merchant_ids', sa.Text(), nullable=False),
    sa.Column('allowed_currencies', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delegations_agent_id'), 'delegations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_delegations_status'), 'delegations', ['status'], unique=False)
    op.create_index(op.f('ix_delegations_user_id'), 'delegations', ['user_id'], unique=False)
    op.create_table('policy_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('max_single_transaction_minor', sa.Integer(), nullable=False),
    sa.Column('daily_limit_minor', sa.Integer(), nullable=False),
    sa.Column('monthly_limit_minor', sa.Integer(), nullable=False),
    sa.Column('require_consent_above_minor', sa.Integer(), nullable=False),
    sa.Column('allowed_categories', sa.Text(), nullable=False),
    sa.Column('allowed_merchant_ids', sa.Text(), nullable=False),
    sa.Column('blocked_merchant_ids', sa.Text(), nullable=False),
    sa.Column('allowed_payment_methods', sa.Text(), nullable=False),
    sa.Column('allowed_currencies', sa.Text(), nullable=False),
    sa.Column('rules_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['spending_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_versions_is_current'), 'policy_versions', ['is_current'], unique=False)
    op.create_index(op.f('ix_policy_versions_policy_id'), 'policy_versions', ['policy_id'], unique=False)
    op.create_table('intents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('discount_minor', sa.Integer(), nullable=False),
    sa.Column('final_amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('payment_method', sa.String(length=16), nullable=False),
    sa.Column('applied_campaign_id', sa.UUID(), nullable=True),
    sa.Column('policy_version_id', sa.UUID(), nullable=True),
    sa.Column('merchant_policy_id', sa.UUID(), nullable=True),
    sa.Column('intent_hash', sa.String(length=64), nullable=False),
    sa.Column('protocol_source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['applied_campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['merchant_policy_id'], ['merchant_policies.id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intent_hash', name='uq_intents_hash')
    )
    op.create_index(op.f('ix_intents_agent_id'), 'intents', ['agent_id'], unique=False)
    op.create_index(op.f('ix_intents_intent_hash'), 'intents', ['intent_hash'], unique=True)
    op.create_index(op.f('ix_intents_merchant_id'), 'intents', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_intents_session_id'), 'intents', ['session_id'], unique=False)
    op.create_index(op.f('ix_intents_status'), 'intents', ['status'], unique=False)
    op.create_index(op.f('ix_intents_user_id'), 'intents', ['user_id'], unique=False)
    op.create_table('capabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intent_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('intent_hash', sa.String(length=64), nullable=False),
    sa.Column('policy_version_id', sa.UUID(), nullable=True),
    sa.Column('merchant_policy_id', sa.UUID(), nullable=True),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_request_id', sa.String(length=64), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['merchant_policy_id'], ['merchant_policies.id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce')
    )
    op.create_index(op.f('ix_capabilities_intent_hash'), 'capabilities', ['intent_hash'], unique=False)
    op.create_index(op.f('ix_capabilities_intent_id'), 'capabilities', ['intent_id'], unique=False)
    op.create_index(op.f('ix_capabilities_status'), 'capabilities', ['status'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intent_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('consent_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consent_token'),
    sa.UniqueConstraint('intent_id', 'user_id', name='uq_consent_intent_user')
    )
    op.create_index(op.f('ix_consents_intent_id'), 'consents', ['intent_id'], unique=False)
    op.create_index(op.f('ix_consents_status'), 'consents', ['status'], unique=False)
    op.create_index(op.f('ix_consents_user_id'), 'consents', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intent_id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=128), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=128), nullable=True),
    sa.Column('policy_decision', sa.String(length=16), nullable=True),
    sa.Column('policy_reason', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('idempotency_key', name='uq_transactions_idempotency')
    )
    op.create_index(op.f('ix_transactions_intent_id'), 'transactions', ['intent_id'], unique=False)
    op.create_index(op.f('ix_transactions_razorpay_order_id'), 'transactions', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_transactions_razorpay_payment_id'), 'transactions', ['razorpay_payment_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('intent_id', sa.UUID(), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('capability_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('policy_version_id', sa.UUID(), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor'), 'audit_events', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_events_intent_id'), 'audit_events', ['intent_id'], unique=False)
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_events_session_id'), 'audit_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_events_transaction_id'), 'audit_events', ['transaction_id'], unique=False)
    op.create_table('payment_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=128), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=128), nullable=True),
    sa.Column('provider_idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_description', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconciliation_source', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_idempotency_key')
    )
    op.create_index(op.f('ix_payment_attempts_razorpay_order_id'), 'payment_attempts', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_razorpay_payment_id'), 'payment_attempts', ['razorpay_payment_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_status'), 'payment_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_payment_attempts_transaction_id'), 'payment_attempts', ['transaction_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('razorpay_event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=128), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=128), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('signature_verified', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sa.String(length=16), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_event_id', name='uq_webhook_razorpay_event_id')
    )
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_processing_status'), 'webhook_events', ['processing_status'], unique=False)
    op.create_index(op.f('ix_webhook_events_razorpay_event_id'), 'webhook_events', ['razorpay_event_id'], unique=True)
    op.create_index(op.f('ix_webhook_events_razorpay_order_id'), 'webhook_events', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_razorpay_payment_id'), 'webhook_events', ['razorpay_payment_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_transaction_id'), 'webhook_events', ['transaction_id'], unique=False)
    op.create_table('reconciliation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('payment_attempt_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('resolved_status', sa.String(length=16), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_source', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_attempt_id'], ['payment_attempts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_jobs_status'), 'reconciliation_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_reconciliation_jobs_transaction_id'), 'reconciliation_jobs', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_jobs_transaction_id'), table_name='reconciliation_jobs')
    op.drop_index(op.f('ix_reconciliation_jobs_status'), table_name='reconciliation_jobs')
    op.drop_table('reconciliation_jobs')
    op.drop_index(op.f('ix_webhook_events_transaction_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_razorpay_payment_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_razorpay_order_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_razorpay_event_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_processing_status'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_payment_attempts_transaction_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_status'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_razorpay_payment_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_razorpay_order_id'), table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_index(op.f('ix_audit_events_transaction_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_session_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_intent_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_razorpay_payment_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_razorpay_order_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_intent_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_consents_user_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_status'), table_name='consents')
    op.drop_index(op.f('ix_consents_intent_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_capabilities_status'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_intent_id'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_intent_hash'), table_name='capabilities')
    op.drop_table('capabilities')
    op.drop_index(op.f('ix_intents_user_id'), table_name='intents')
    op.drop_index(op.f('ix_intents_status'), table_name='intents')
    op.drop_index(op.f('ix_intents_session_id'), table_name='intents')
    op.drop_index(op.f('ix_intents_merchant_id'), table_name='intents')
    op.drop_index(op.f('ix_intents_intent_hash'), table_name='intents')
    op.drop_index(op.f('ix_intents_agent_id'), table_name='intents')
    op.drop_table('intents')
    op.drop_index(op.f('ix_policy_versions_policy_id'), table_name='policy_versions')
    op.drop_index(op.f('ix_policy_versions_is_current'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_delegations_user_id'), table_name='delegations')
    op.drop_index(op.f('ix_delegations_status'), table_name='delegations')
    op.drop_index(op.f('ix_delegations_agent_id'), table_name='delegations')
    op.drop_table('delegations')
    op.drop_index(op.f('ix_consent_mandates_user_id'), table_name='consent_mandates')
    op.drop_index(op.f('ix_consent_mandates_status'), table_name='consent_mandates')
    op.drop_index(op.f('ix_consent_mandates_merchant_id'), table_name='consent_mandates')
    op.drop_index(op.f('ix_consent_mandates_agent_id'), table_name='consent_mandates')
    op.drop_table('consent_mandates')
    op.drop_index(op.f('ix_spending_policies_user_id'), table_name='spending_policies')
    op.drop_index(op.f('ix_spending_policies_is_active'), table_name='spending_policies')
    op.drop_table('spending_policies')
    op.drop_index(op.f('ix_merchant_policies_merchant_id'), table_name='merchant_policies')
    op.drop_index(op.f('ix_merchant_policies_is_current'), table_name='merchant_policies')
    op.drop_table('merchant_policies')
    op.drop_index(op.f('ix_catalog_products_sku'), table_name='catalog_products')
    op.drop_index(op.f('ix_catalog_products_merchant_id'), table_name='catalog_products')
    op.drop_index(op.f('ix_catalog_products_category'), table_name='catalog_products')
    op.drop_index(op.f('ix_catalog_products_availability'), table_name='catalog_products')
    op.drop_table('catalog_products')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_merchant_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_code'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_agents_user_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_merchants_status'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_razorpay_merchant_id'), table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###
